### ISSUE TITLE
Create post pop-up page

### ISSUE THREAD

**Issue by Drakesinger** [HE-Arc/meetING#6]
The page will allow the user to enter his Name, Surname, Email address and say confirm whether or not the post corresponds to him.

Inputs:
- [ ] Name
- [ ] Surname
- [ ] Email address

Buttons:
- [ ] Confirm
- [ ] Cancel

Check out: [materialize](http://materializecss.com/modals.html) for how to do it.

**Comment by greut** [comment]
popup? rly?

**Comment by Drakesinger** [comment]
What would you call it?

**Comment by greut** [comment]
ceci est un popup : [`window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open)

**Comment by Drakesinger** [comment]
The same question applies.

**Comment by greut** [comment]
What you think is correct but the words chosen aren't. Hence, I'm confused by your intentions.

A _popup_ is **not** modal and is usually blocked by the browser.

[Modal](https://en.wikipedia.org/wiki/Modal_window) or [dialog](http://caniuse.com/#feat=dialog) [windows](https://www.quora.com/Whats-the-difference-between-a-modal-a-popover-and-a-popup) are what you probably means.

Just check that it works on a small screen though.

**Comment by Drakesinger** [comment]
Probably dialog window is the the better word. The problem is that it's not a "window".
Internal pop-up :P

**Comment by Drakesinger** [comment]
The feature was dropped during development as it:
- was a bad idea
- used Javascript
- required Javascript
- mixed Ruby & Javascript
